name: Copilot Setup Steps

on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Install Task
        uses: go-task/setup-task@v2

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          install-only: true

      - name: Install Changie
        run: go install github.com/miniscruff/changie@latest

      - name: golangci-lint
        continue-on-error: true
        uses: golangci/golangci-lint-action@v9
        with:
          args: --issues-exit-code=0 --timeout=5m
