name: Dependabot add changie file
on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write
  issues: write
  repository-projects: write
  contents: write

jobs:
  dependabot-changie:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Fetch Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@25dd0e34f4fe68f24cc83900b1fe3fe149efef98 # v3.1.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Create change file
        uses: miniscruff/changie-action@11bcad388e7973948cbcecb10863baf024d5f607 # v3.0.0
        with:
          version: latest
          args: new --body "${{ github.event.pull_request.title }}" --kind Dependency

      - uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: "chore(deps): add changelog for dependabot updates"
          commit_user_name: "dependabot[bot]"
          commit_user_email: "dependabot[bot]@users.noreply.github.com"
