name: Pinact

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"

permissions: {}

jobs:
  pinact:
    # Only run on pull requests from the same repository
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Pin actions
        uses: suzuki-shunsuke/pinact-action@896d595f299e71d65b9d28349d6956abe144390a # v3.0.0
        with:
          skip_push: true
          verify: true
          min_age: 7
