name: Run Tests

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest

    services:
      commercetools:
        image: labdigital/commercetools-mock-server:3.0.0-beta.3
        ports:
        - 8989:8989

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: go.mod
        cache: false

    - name: golangci-lint
      continue-on-error: true
      uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
      with:
        args: --issues-exit-code=0 --timeout=5m

    - name: Run tests
      run: go test -timeout 30m -race -coverprofile=coverage.out -covermode=atomic -coverpkg=./... ./...
      env:
        TF_ACC: 1
        CTP_CLIENT_ID: unittest
        CTP_CLIENT_SECRET: x
        CTP_PROJECT_KEY: unittest
        CTP_SCOPES: manage_project:unittest
        CTP_API_URL: http://localhost:8989
        CTP_AUTH_URL: http://localhost:8989

    - name: Upload to codecov
      uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
      with:
        verbose: true

    - name: build binary
      uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
      with:
        args: build --snapshot --clean --single-target
      env:
        GOPATH: ${{ env.GOPATH }}

  changie:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    permissions:
      contents: write
      pull-requests: write
      actions: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Prepare release
        uses: labd/changie-release-action@43112f435367957ee3fefc64b3b712c7e672be33 # v0.6.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-workflow: 'release.yaml'
